# Generated by Django 4.1.5 on 2023-07-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_life_product_mfs_product_stock_conut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mfs',
            new_name='mfd',
        ),
    ]
